# Generated by Django 5.0.3 on 2024-03-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categories',
        ),
    ]
